# -*- coding: utf-8 -*- data collection, cleaning, eda analysis
"""Global_Literacy_and_GDP_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1imS9c3wpQZNCxPuUwDeHJxoW_iWKtvEn

--------------------------------------------------------------------------------
# **Author** : ***Mohamed Halith M K***
## **Title**  : ***Global Literacy and GDP Analysis***
### **Type**   : ***GUVI Mini Projects - 2***
--------------------------------------------------------------------------------

# **Data Collection**
"""

#imported required libraries for this project
import pandas as pd
import numpy as np

# data collection

urls = {
    "adult": "https://ourworldindata.org/grapher/literacy-rate-adults.csv?v=1&csvType=full&useColumnShortNames=true",
    "youth": "https://ourworldindata.org/grapher/literacy-rate-of-young-men-and-women.csv?v=1&csvType=full&useColumnShortNames=true",
    "illiteracy": "https://ourworldindata.org/grapher/literate-and-illiterate-world-population.csv?v=1&csvType=full&useColumnShortNames=true",
    "gdp": "https://ourworldindata.org/grapher/gdp-per-capita-worldbank.csv?v=1&csvType=full&useColumnShortNames=true",
    "schooling": "https://ourworldindata.org/grapher/literacy-rates-vs-average-years-of-schooling.csv?v=1&csvType=full&useColumnShortNames=true"
    }

datasets = {}

for name, url in urls.items():

    datasets[name] = pd.read_csv(
        url,
        storage_options={
            "User-Agent": "Our World In Data data fetch/1.0"
        }
    )

df_adult = datasets["adult"]
df_youth = datasets["youth"]
df_illiteracy = datasets["illiteracy"]
df_gdp = datasets["gdp"]
df_schooling = datasets["schooling"]

"""# **Data cleaning**

###**1. Standardize country & region names for merging**
"""

# List of dataframe-column pairs
datasets = [
    (df_adult, ["entity"]),
    (df_youth, ["entity", "owid_region"]),
    (df_illiteracy, ["entity"]),
    (df_gdp, ["entity", "owid_region"]),
    (df_schooling, ["entity", "owid_region"])
]

# Apply title case
for df, cols in datasets:
    for col in cols:
        df[col] = df[col].str.title()

"""###**2. Mereging Data Frames**"""

# df_literacy → Adult & Youth Literacy Rates
df_literacy = pd.merge(df_adult, df_youth, on=['entity', 'code', 'year'], how = 'left')

df_literacy

# df_gdp_schooling → GDP & Years of Schooling
df_gdp_schooling = pd.merge(df_gdp, df_schooling, on=['entity', 'code', 'year', 'owid_region'], how = 'left')

df_gdp_schooling

"""###**3. Rename column names for clarity**"""

# df_literacy
df_literacy.rename(columns={"entity" : "Country",
                            "code" : "Code",
                            "year" : "Year",
                            "adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99" : "Adult",
                            "youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m" : "Male",
                            "youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f" : "Female",
                            "owid_region" : "Region"},inplace=True)

df_literacy

# df_illiteracy
df_illiteracy.rename(columns={'entity': 'Country',
                                'illiteracy_rate' : 'Illiteracy_rate',
                                'literacy_rate' : 'Literacy_rate',
                                'year' : 'Year',
                                'code' : 'Code',}, inplace=True)

df_illiteracy

# df_gdp_schooling
df_gdp_schooling.rename(columns={"entity": "Country",
                                 "code" : "Code",
                                 "year" : "Year",
                                 "owid_region" : "Region",
                                 "ny_gdp_pcap_pp_kd" : "GDP",
                                 "literacy_rate" : "Literacy",
                                 "mf_youth_and_adults__15_64_years__average_years_of_education" : "Avg_yrs_schooling",
                                 "population_historical" : "Population"}, inplace=True)

df_gdp_schooling

"""###**4. Find and Remove duplicates**"""

df_literacy.drop_duplicates(inplace=True) # modify
df_literacy

df_illiteracy.drop_duplicates(inplace=True)
df_illiteracy

df_gdp_schooling.drop_duplicates(inplace=True)
df_gdp_schooling

"""###**5. Handle missing values: Drop or impute & reseting index**"""

# df_literacy
df_literacy.isnull().sum() # find null or missing values and count

cols = ["Code", "Region", "Male", "Female"] #impute null or missing value

for col in cols:
    if col in ["Code", "Region"]:
        df_literacy[col] = df_literacy[col].fillna(
            df_literacy[col].mode()[0]
        ) # for str columns
    else:
        # numerical columns
        df_literacy[col] = df_literacy[col].fillna(
            df_literacy[col].median()
        )

print(df_literacy.isnull().sum()) # verification for missing values are imputed or not

df_literacy

# df_illiteracy
print(df_illiteracy.isnull().sum())

df_illiteracy["Code"] = df_illiteracy["Code"].fillna(df_illiteracy["Code"].mode()[0])

print(df_illiteracy.isnull().sum())

df_illiteracy

# df_gdp_schooling
df_gdp_schooling

print(df_gdp_schooling.isnull().sum())

columns = ['GDP', "Region", 'Avg_yrs_schooling', "Literacy", "Population"]

for c in columns:
    if c in ["Region"]:
        df_gdp_schooling[c] = df_gdp_schooling[c].fillna(df_gdp_schooling[c].mode()[0])
    else:
        df_gdp_schooling[c] = df_gdp_schooling[c].fillna(df_gdp_schooling[c].median())

print(df_gdp_schooling.isnull().sum())

df_gdp_schooling

"""###**6. Understand the shape and structure of the data**

**df_literacy**
"""

df_literacy.head()

df_literacy.info() # to quickly understand the structure and basic details of your dataset

df_literacy.shape # check how big is the data

df_literacy.dtypes # checking the data types of columns

df_literacy.describe() # To get the quick overview/snapshot of key summary statistics

"""**df_illiteracy**"""

# df_illiteracy
df_illiteracy.head()

df_illiteracy.info()

df_illiteracy.shape

df_illiteracy.dtypes

df_illiteracy.describe()

"""****df_gdp_schooling****"""

# df_gdp_schooling
df_gdp_schooling.head()

df_gdp_schooling.info()

df_gdp_schooling.shape

print(df_gdp_schooling.dtypes)

print(df_gdp_schooling.describe())

"""###**7. Filter years between 1990 - 2023 (or last year in the data collected)**"""

df_literacy

# df_literacy
df_literacy = df_literacy[(df_literacy['Year'] >= 1990) & (df_literacy['Year'] <= 2023)]
df_literacy

# reset index after fillter data between 1990 to 2023
df_literacy = df_literacy.reset_index(drop=True)
df_literacy

df_literacy = df_literacy.round(2)
df_literacy

# df_illitercy
df_illiteracy["Year"].min()

df_illiteracy["Year"].max()

# df_illiteracy
df_illiteracy = df_illiteracy[(df_illiteracy['Year'] >= 1990) & (df_illiteracy['Year'] <= 2023)]
df_illiteracy

df_illiteracy = df_illiteracy.reset_index(drop=True)
df_illiteracy

df_illiteracy = df_illiteracy.round(2)
df_illiteracy

# df_gdp_schooling
df_gdp_schooling = df_gdp_schooling[(df_gdp_schooling['Year'] >= 1990) & (df_gdp_schooling['Year'] <= 2023)]
df_gdp_schooling

df_gdp_schooling = df_gdp_schooling.reset_index(drop=True)
df_gdp_schooling

df_gdp_schooling["GDP"] = np.round(df_gdp_schooling["GDP"],decimals = 2)
df_gdp_schooling["Literacy"] = np.round(df_gdp_schooling["Literacy"],decimals = 2)
df_gdp_schooling["Avg_yrs_schooling"] = np.round(df_gdp_schooling["Avg_yrs_schooling"],decimals = 2)
df_gdp_schooling["Population"] = np.round(df_gdp_schooling["Population"],decimals = 2)
df_gdp_schooling

df_gdp_schooling

"""#**Merge Population column to Litracy and Illiteracy DataFrame for EDA**"""

df_population = df_gdp_schooling[["Country", "Code", "Year", "Population"]].copy() #extract population column
df_population

# Lliteracy
df_literacy = pd.merge(df_literacy, df_population, on=["Country", "Code", "Year"], how = 'left') # merging for better eda
df_literacy

print(df_literacy.isnull().sum())

df_literacy["Population"] = df_literacy["Population"].fillna(df_literacy["Population"].median())

print(df_literacy.isnull().sum())

# Illiteracy
df_illiteracy = pd.merge(df_illiteracy, df_population, on=["Country", "Code", "Year"], how = 'left')
df_illiteracy

print(df_illiteracy.isnull().sum())

df_illiteracy["Population"] = df_illiteracy["Population"].fillna(df_illiteracy["Population"].median())

print(df_illiteracy.isnull().sum())

"""# **Feature Engineering**"""

# 1. Illiteracy % Shows the percentage of the population that is illiterate
df_illiteracy

df_illiteracy["Illiteracy_Population"] = (df_illiteracy["Illiteracy_rate"] / 100 ) * df_illiteracy["Population"].astype(int)
df_illiteracy

print(df_illiteracy.isnull().sum())

# 2. Literacy Gender Gap Highlights the disparity between male and female literacy rates.
df_literacy

# calculating literacy gap between gender and create column
df_literacy["Literacy_gap"] = df_literacy["Male"] - df_literacy["Female"]
df_literacy

# 3. Youth Literacy Average Provides a single indicator for overall youth literacy.
df_literacy

# I create new column to get the total youth population   || to calculate overall youth literacy rate
df_literacy["Total_Youth"] = df_literacy["Male"] + df_literacy["Female"]
df_literacy

# calculate the overall youth lliteracy avg and create column
df_literacy["Avg_Youth_Literacy"] = df_literacy[["Male", "Female"]].mean(axis = 1) # Calculates the average across columns (row-wise)
df_literacy

print(df_literacy.isnull().sum())

# 4. GDP per Schooling Year Helps analyze economic output per year of education.
df_gdp_schooling

# calculate gdp per schooling and create column
df_gdp_schooling["GDP_per_Schooling"] = df_gdp_schooling["GDP"] / df_gdp_schooling["Avg_yrs_schooling"]
df_gdp_schooling

# 5. Education Index Measures education quality by considering both access (literacy) and duration (schooling).
df_gdp_schooling

# | EI Value    | Category  |
# | ----------- | --------- |
# | 0.900+      | Very High |
# | 0.700-0.899 | High      |
# | 0.500-0.699 | Medium    |
# | <0.500      | Low       |

df_gdp_schooling['Education_Index'] = \
    (df_gdp_schooling['Literacy'] / 100) * (df_gdp_schooling['Avg_yrs_schooling'] / 15)

df_gdp_schooling

# 6. Literacy Growth Rate Measures year-over-year improvement in literacy.
df_gdp_schooling["Growth_Rate"] = (df_gdp_schooling["Literacy"].pct_change() * 100).fillna(0)
df_gdp_schooling

print(df_gdp_schooling.isnull().sum())

"""**Saving this DaraFrames as .csv file**

"""

df_literacy

df_illiteracy

df_gdp_schooling

df_literacy.to_csv("df_literacy.csv", index=False)
df_illiteracy.to_csv("df_illiteracy.csv", index=False)
df_gdp_schooling.to_csv("df_gdp_schooling.csv", index=False)

"""#**Exploratory Data Analysis (EDA)**"""

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

"""***Literacy EDA***

**1. Adult & Youth Literacy Rate Over Years**
"""

df_literacy

adult_literacy = df_literacy.groupby("Year")["Adult"].mean()
youth_literacy = df_literacy.groupby("Year")["Total_Youth"].mean()

plt.figure(figsize=(15,8))
plt.plot(youth_literacy.index, youth_literacy.values)
plt.plot(adult_literacy.index, adult_literacy.values)
plt.title("Avg Literacy Rate Over Years of Adult & Youth")
plt.xlabel("Year")
plt.ylabel("Total_Youth & Adult")
plt.legend(["Youth", "Adult"])
plt.grid(alpha=0.5)

plt.show()

"""**2. Region wise Male and Female Literacy Rate**"""

r_male_literacy = df_literacy.groupby("Region")["Male"].mean()
r_female_literacy = df_literacy.groupby("Region")["Female"].mean()

plt.figure(figsize=(15,8))
plt.plot(r_male_literacy.index, r_male_literacy.values, marker="o")
plt.plot(r_female_literacy.index, r_female_literacy.values, marker="o")
plt.title("Region Wise Trend")
plt.xlabel("Region")
plt.ylabel("Total_Youth")
plt.grid(alpha=0.5)
plt.legend(["Male", "Female"])

plt.show()

"""**3. Adult Literacy during covid (2020 to 2023)**"""

covid_year = df_literacy[(df_literacy["Year"] >= 2020) & (df_literacy["Year"] <= 2023)]
adult_literacy = covid_year.groupby("Year", as_index=False)["Adult"].mean().round()

plt.figure(figsize=(15,8))

sns.barplot(data=adult_literacy, x="Year", y="Adult", palette="dark", width=0.25, hue="Adult")

plt.title("Adult Literacy During COVID (2020 to 2023)")
plt.xlabel("Year")
plt.ylabel("Adult Literacy")
plt.legend(loc="upper center")

plt.grid(False)

plt.show()

fig = px.line(adult_literacy, x="Year", y="Adult", markers=True, title="Adult Literacy During COVID")

fig.show()

"""**4. Indain Youth Leteracy Rate Over Years**"""

india_literacy = df_literacy[df_literacy["Country"] == "India"]

plt.figure(figsize=(20,10))
plt.pie(india_literacy["Total_Youth"], labels=india_literacy["Year"], autopct='%1.1f%%')
plt.title("Youth Leteracy Rate Over Years - Inida")
plt.legend(loc="upper right")

plt.show()

"""***Illiteracy EDA***

**5. Illiterates vs Literates trend over Years**
"""

illiteracy = df_illiteracy.groupby("Year")["Illiteracy_rate"].mean()
literacy = df_illiteracy.groupby("Year")["Literacy_rate"].mean()

plt.figure(figsize=(15,8))
plt.bar(illiteracy.index,illiteracy.values)
plt.bar(literacy.index, literacy.values, alpha=0.7)
plt.title("Illiterates and Literates trand over Years")
plt.xlabel("Year")
plt.ylabel("Trend")
plt.legend(["Illiterates", "Literates"])
plt.yticks(range(0, 101, 10))
plt.grid(alpha=0.5)

plt.show()

"""**6. Illiteracy Rate comparision betweeen selected countries over years**"""

countries = ["Bangladesh", "China", "India", "Nepal", "Pakistan"]

com_countries = df_illiteracy[df_illiteracy["Country"].isin(countries)]

plt.figure(figsize=(15,8))
sns.barplot(data=com_countries, x="Year", y="Illiteracy_rate", palette= "magma", width=1, hue="Country")

plt.title("Illiteracy Rate of Five Countries(random)")
plt.xlabel("Year")
plt.ylabel("Illiteracy Rate")
plt.legend(loc="upper right")

plt.grid(False)

plt.show()

"""***GDP and Schooling EDA***

**7. GPD per Avg Schooling**
"""

plt.figure(figsize=(15,6))

sns.scatterplot(data = df_gdp_schooling, x="Avg_yrs_schooling", y="GDP")

plt.title("GDP vs Schooling")
plt.xlabel("Schooling")
plt.ylabel("GDP")
plt.grid(True, alpha=0.5)


plt.show()

"""**8. Highest GDP countries literacy rate TOP 5 only**"""

top_gdp = df_gdp_schooling.groupby("Country")[["GDP", "Literacy"]] \
                          .mean() \
                          .sort_values(by="GDP", ascending=False) \
                          .head(5) #\ line continue

plt.figure(figsize=(15,8))

sns.barplot(x = top_gdp.index, y = top_gdp["Literacy"], palette = "viridis", hue = top_gdp["GDP"],
            width = 0.25)

plt.title("Literacy Rate of Highest GDP Countries")
plt.xlabel("Country")
plt.ylabel("Literacy Rate")
plt.grid(False)

plt.show()

"""**9. Literacy Growth Rate over year - India.**"""

ind = df_gdp_schooling[df_gdp_schooling["Country"] == "India"].copy()
growth = ind.groupby("Year")["Growth_Rate"].mean().reset_index()

fig = px.line(growth, x="Year", y="Growth_Rate", title="Literacy Growth Rate over year - India", markers=True, line_shape='spline')

fig.update_layout(width=1000, height=600, title_x=0.5)
fig.update_traces(line=dict(color='orange', width=4))

fig.show()

"""**10. Population Growth vs Literacy Growth - Covid**"""

covid = df_gdp_schooling[(df_gdp_schooling["Year"] >= 2020) & (df_gdp_schooling["Year"] <= 2023)]

population_literacy = covid.groupby("Year", as_index=False).agg ({"Population": "max", "Literacy": "mean"})

population_literacy["Year"] = population_literacy["Year"].astype(int)

fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(go.Bar(x=population_literacy["Year"],y=population_literacy["Population"] / 1_000_000,name="Population (Million)"),secondary_y=False)

fig.add_trace(go.Scatter(x=population_literacy["Year"], y=population_literacy["Literacy"], mode="lines+markers", name="Literacy Rate (%)"), secondary_y=True)

fig.update_layout(title="Population Growth vs Literacy Growth - Covid",width=900, height=600, template="plotly_white")

fig.update_xaxes(title_text="Year")
fig.update_yaxes (title_text="Population (Millions)", secondary_y=False)
fig.update_yaxes(title_text="Literacy Rate (%)", secondary_y=True)

fig.show()

"""**11. GDP Distribution Boxplot**"""

plt.figure(figsize=(15,8))

sns.boxplot(
    data=df_gdp_schooling,
    x="Year",
    y="GDP",
    palette="viridis",
    hue = "Year"
)

plt.title("GDP Distribution Over Years")
plt.xlabel("Year")
plt.ylabel("GDP")

plt.xticks(rotation=45)

plt.grid(alpha=0.5)

plt.show()

"""**12. Correlation of Population and Literacy**"""

df_gdp_schooling = df_gdp_schooling.sort_values(["Year", "Population"])

population_literacy = df_gdp_schooling.groupby("Year", as_index=False).agg ({"Population": "max", "Literacy": "mean"})

fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(go.Bar(x=population_literacy["Year"],y=population_literacy["Population"] / 1_000_000,name="Population (Million)"),secondary_y=False)
fig.add_trace(go.Scatter(x=population_literacy["Year"], y=population_literacy["Literacy"], mode="lines+markers", name="Literacy Rate (%)"), secondary_y=True)
fig.update_layout(title="Population vs Literacy Rate Over Years",width=1100, height=600, title_x=0.5, template="plotly_white")

fig.update_xaxes(title_text="Year")
fig.update_yaxes (title_text="Population (Millions)", secondary_y=False)
fig.update_yaxes(title_text="Literacy Rate (%)", secondary_y=True)

fig.show()
