# -*- coding: utf-8 -*-
"""Global_Lit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1imS9c3wpQZNCxPuUwDeHJxoW_iWKtvEn
"""

#imported required libraries for this project
import pandas as pd
import numpy as np

"""# **Data Collection**"""

# data collection for adult literacy
df_adult = pd.read_csv("https://ourworldindata.org/grapher/literacy-rate-adults.csv?v=1&csvType=full&useColumnShortNames=true",
                       storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

df_adult

# data collection for Youth literacy
df_youth = pd.read_csv("https://ourworldindata.org/grapher/literacy-rate-of-young-men-and-women.csv?v=1&csvType=full&useColumnShortNames=true",
                       storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

df_youth

# data collection for total illiteracy population
df_illiteracy = pd.read_csv("https://ourworldindata.org/grapher/literate-and-illiterate-world-population.csv?v=1&csvType=full&useColumnShortNames=true",
                          storage_options ={'User-Agent': 'Our World In Data data fetch/1.0'})

df_illiteracy

# data collection for gdp
df_gdp = pd.read_csv(
    "https://ourworldindata.org/grapher/gdp-per-capita-worldbank.csv?v=1&csvType=full&useColumnShortNames=true",
    storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

df_gdp

# data collection for avg schooling
df_schooling = pd.read_csv(
    "https://ourworldindata.org/grapher/literacy-rates-vs-average-years-of-schooling.csv?v=1&csvType=full&useColumnShortNames=true",
    storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

df_schooling

"""# **Data cleaning**

###**1. Standardize country & region names for merging**
"""

# adult literacy
df_adult['entity'].str.title()
# youth literacy
df_youth['entity'].str.title()
df_youth['owid_region'].str.title()
# illiteracy population
df_illiteracy['entity'].str.title()
# gdp
df_gdp['entity'].str.title()
df_gdp['owid_region'].str.title()
# schooling
df_schooling['entity'].str.title()
df_schooling['owid_region'].str.title()

"""###**2. Mereging Data Frames**"""

# df_literacy → Adult & Youth Literacy Rates
df_literacy = pd.merge(df_adult, df_youth, on=['entity', 'code', 'year'], how = 'left')

df_literacy

# df_gdp_schooling → GDP & Years of Schooling
df_gdp_schooling = pd.merge(df_gdp, df_schooling, on=['entity', 'code', 'year', 'owid_region'], how = 'left')

df_gdp_schooling

"""###**3. Rename column names for clarity**"""

# df_literacy
df_literacy.rename(columns={"entity" : "Country",
                            "code" : "Code",
                            "year" : "Year",
                            "adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99" : "Adult",
                            "youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m" : "Male",
                            "youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f" : "Female",
                            "owid_region" : "Region"},inplace=True)

df_literacy

# df_illiteracy
df_illiteracy.rename(columns={'entity': 'Country',
                                'illiteracy_rate' : 'Illiteracy_rate',
                                'literacy_rate' : 'Literacy_rate',
                                'year' : 'Year',
                                'code' : 'Code',}, inplace=True)

df_illiteracy

# df_gdp_schooling
df_gdp_schooling.rename(columns={"entity": "Country",
                                 "code" : "Code",
                                 "year" : "Year",
                                 "owid_region" : "Region",
                                 "ny_gdp_pcap_pp_kd" : "GDP",
                                 "literacy_rate" : "Literacy",
                                 "mf_youth_and_adults__15_64_years__average_years_of_education" : "Avg_yrs_schooling",
                                 "population_historical" : "Population"}, inplace=True)

df_gdp_schooling

"""###**4. Find and Remove duplicates**"""

df_literacy.drop_duplicates(inplace=True) # modify
df_literacy

df_illiteracy.drop_duplicates(inplace=True)
df_illiteracy

df_gdp_schooling.drop_duplicates(inplace=True)
df_gdp_schooling

"""###**5. Handle missing values: Drop or impute & reseting index**"""

# df_literacy
df_literacy.isnull().sum() # find null and count

cols = ["Code", "Region", "Male", "Female"]

for col in cols:
    if col in ["Code", "Region"]:
        # categorical columns
        df_literacy[col] = df_literacy[col].fillna(
            df_literacy[col].mode()[0]
        )
    else:
        # numerical columns
        df_literacy[col] = df_literacy[col].fillna(
            df_literacy[col].median()
        )

print(df_literacy.isnull().sum()) # for verification of imputing missing values

df_literacy

# df_illiteracy
print(df_illiteracy.isnull().sum())

df_illiteracy["Code"] = df_illiteracy["Code"].fillna(df_illiteracy["Code"].mode()[0])

print(df_illiteracy.isnull().sum()) # for verification of droping missing values

df_illiteracy

# df_gdp_schooling
df_gdp_schooling

print(df_gdp_schooling.isnull().sum())

columns = ['GDP', "Region", 'Avg_yrs_schooling', "Literacy", "Population"]

for c in columns:
    if c in ["Region"]:
        df_gdp_schooling[c] = df_gdp_schooling[c].fillna(df_gdp_schooling[c].mode()[0])
    else:
        df_gdp_schooling[c] = df_gdp_schooling[c].fillna(df_gdp_schooling[c].median())

print(df_gdp_schooling.isnull().sum())

df_gdp_schooling

"""###**6. Understand the shape and structure of the data**"""

df_literacy.head()

df_literacy.info() # to quickly understand the structure and basic details of your dataset

df_literacy.shape # check how big is the data

df_literacy.dtypes # checking the data types of columns

df_literacy.describe() # To get the quick overview/snapshot of key summary statistics

# df_illiteracy
df_illiteracy.head()

df_illiteracy.info()

df_illiteracy.shape

df_illiteracy.dtypes

df_illiteracy.describe()

# df_gdp_schooling
df_gdp_schooling.head()

df_gdp_schooling.info()

df_gdp_schooling.shape

print(df_gdp_schooling.dtypes)

print(df_gdp_schooling.describe())

"""###**7. Filter years between 1990 - 2023 (or last year in the data collected)**"""

df_literacy

# df_literacy
df_literacy = df_literacy[(df_literacy['Year'] >= 1990) & (df_literacy['Year'] <= 2023)]
df_literacy

# reset index after fillter data between 1990 to 2023
df_literacy = df_literacy.reset_index(drop=True)
df_literacy

df_literacy = df_literacy.round(2)
df_literacy

# df_illitercy
df_illiteracy["Year"].min()

df_illiteracy["Year"].max()

# df_illiteracy
df_illiteracy = df_illiteracy[(df_illiteracy['Year'] >= 1990) & (df_illiteracy['Year'] <= 2023)]
df_illiteracy

df_illiteracy = df_illiteracy.reset_index(drop=True)
df_illiteracy

df_illiteracy = df_illiteracy.round(2)
df_illiteracy

# df_gdp_schooling
df_gdp_schooling = df_gdp_schooling[(df_gdp_schooling['Year'] >= 1990) & (df_gdp_schooling['Year'] <= 2023)]
df_gdp_schooling

df_gdp_schooling = df_gdp_schooling.reset_index(drop=True)
df_gdp_schooling

df_gdp_schooling["GDP"] = np.round(df_gdp_schooling["GDP"],decimals = 2)
df_gdp_schooling["Literacy"] = np.round(df_gdp_schooling["Literacy"],decimals = 2)
df_gdp_schooling["Avg_yrs_schooling"] = np.round(df_gdp_schooling["Avg_yrs_schooling"],decimals = 2)
df_gdp_schooling["Population"] = np.round(df_gdp_schooling["Population"],decimals = 2)
df_gdp_schooling

df_gdp_schooling

"""#**Merge Population to Litracy and Illiteracy DataFrame for EDA**"""

df_population = df_gdp_schooling[["Country", "Code", "Year", "Population"]].copy() #extract population column
df_population

# Lliteracy
df_literacy = pd.merge(df_literacy, df_population, on=["Country", "Code", "Year"], how = 'left') # merging for better eda
df_literacy

print(df_literacy.isnull().sum())

df_literacy["Population"] = df_literacy["Population"].fillna(df_literacy["Population"].median())

print(df_literacy.isnull().sum())

# Illiteracy
df_illiteracy = pd.merge(df_illiteracy, df_population, on=["Country", "Code", "Year"], how = 'left')
df_illiteracy

print(df_illiteracy.isnull().sum())

df_illiteracy["Population"] = df_illiteracy["Population"].fillna(df_illiteracy["Population"].median())

print(df_illiteracy.isnull().sum())

"""# **Feature Engineering**"""

# 1. Illiteracy % Shows the percentage of the population that is illiterate
df_illiteracy

df_illiteracy["Illiteracy_Population"] = (df_illiteracy["Illiteracy_rate"] / 100 ) * df_illiteracy["Population"].astype(int)
df_illiteracy

print(df_illiteracy.isnull().sum())

# 2. Literacy Gender Gap Highlights the disparity between male and female literacy rates.
df_literacy

# calculating literacy gap between gender and create column
df_literacy["Literacy_gap"] = df_literacy["Male"] - df_literacy["Female"]
df_literacy

# 3. Youth Literacy Average Provides a single indicator for overall youth literacy.
df_literacy

# I create new column to get the total youth population   || to calculate overall youth literacy rate
df_literacy["Total_Youth"] = df_literacy["Male"] + df_literacy["Female"]
df_literacy

# calculate the overall youth lliteracy avg and create column
df_literacy["Avg_Youth_Literacy"] = df_literacy[["Male", "Female"]].mean(axis = 1) # Calculates the average across columns (row-wise)
df_literacy

print(df_literacy.isnull().sum())

# 4. GDP per Schooling Year Helps analyze economic output per year of education.
df_gdp_schooling

# calculate gdp per schooling and create column
df_gdp_schooling["GDP_per_Schooling"] = df_gdp_schooling["GDP"] / df_gdp_schooling["Avg_yrs_schooling"]
df_gdp_schooling

# 5. Education Index Measures education quality by considering both access (literacy) and duration (schooling).
df_gdp_schooling

# | EI Value    | Category  |
# | ----------- | --------- |
# | 0.900+      | Very High |
# | 0.700-0.899 | High      |
# | 0.500-0.699 | Medium    |
# | <0.500      | Low       |

df_gdp_schooling['Education_Index'] = \
    (df_gdp_schooling['Literacy'] / 100) * (df_gdp_schooling['Avg_yrs_schooling'] / 15)

df_gdp_schooling

# 6. Literacy Growth Rate Measures year-over-year improvement in literacy.
df_gdp_schooling["Growth_Rate"] = (df_gdp_schooling["Literacy"].pct_change() * 100).fillna(0)
df_gdp_schooling

print(df_gdp_schooling.isnull().sum())

"""**Saving this DaraFrames as .csv file**

"""

df_literacy

df_illiteracy

df_gdp_schooling

df_literacy.to_csv("df_literacy.csv", index=False)
df_illiteracy.to_csv("df_illiteracy.csv", index=False)
df_gdp_schooling.to_csv("df_gdp_schooling.csv", index=False)

"""#**Exploratory Data Analysis (EDA)**"""

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

"""***Literacy EDA***

**1. Adult & Youth Literacy Rate Over Years**
"""

df_literacy

adult_literacy = df_literacy.groupby("Year")["Adult"].mean()
youth_literacy = df_literacy.groupby("Year")["Total_Youth"].mean()

plt.figure(figsize=(15,8))
plt.plot(youth_literacy.index, youth_literacy.values)
plt.plot(adult_literacy.index, adult_literacy.values)
plt.title("Avg Literacy Rate Over Years of Adult & Youth")
plt.xlabel("Year")
plt.ylabel("Total_Youth & Adult")
plt.legend(["Youth", "Adult"])
plt.grid(alpha=0.5)

plt.show()

"""**2. Region wise Male and Female Literacy Rate**"""

r_male_literacy = df_literacy.groupby("Region")["Male"].mean()
r_female_literacy = df_literacy.groupby("Region")["Female"].mean()

plt.figure(figsize=(15,8))
plt.plot(r_male_literacy.index, r_male_literacy.values, marker="o")
plt.plot(r_female_literacy.index, r_female_literacy.values, marker="o")
plt.title("Region Wise Trend")
plt.xlabel("Region")
plt.ylabel("Total_Youth")
plt.grid(alpha=0.5)
plt.legend(["Male", "Female"])

plt.show()

"""**3. Adult Literacy during covid (2020 to 2023)**"""

covid_year = df_literacy[(df_literacy["Year"] >= 2020) & (df_literacy["Year"] <= 2023)]
adult_literacy = covid_year.groupby("Year", as_index=False)["Adult"].mean().round()

plt.figure(figsize=(15,8))

sns.barplot(data=adult_literacy, x="Year", y="Adult", palette="dark", width=0.25, hue="Adult")

plt.title("Adult Literacy During COVID (2020 to 2023)")
plt.xlabel("Year")
plt.ylabel("Adult Literacy")
plt.legend(loc="upper center")

plt.grid(False)

plt.show()

fig = px.line(adult_literacy, x="Year", y="Adult", markers=True, title="Adult Literacy During COVID")

fig.show()

"""**4. Indain Youth Leteracy Rate Over Years**"""

india_literacy = df_literacy[df_literacy["Country"] == "India"]

plt.figure(figsize=(20,10))
plt.pie(india_literacy["Total_Youth"], labels=india_literacy["Year"], autopct='%1.1f%%')
plt.title("Youth Leteracy Rate Over Years - Inida")
plt.legend(loc="upper right")

plt.show()

"""***Illiteracy EDA***

**5. Illiterates vs Literates trend over Years**
"""

illiteracy = df_illiteracy.groupby("Year")["Illiteracy_rate"].mean()
literacy = df_illiteracy.groupby("Year")["Literacy_rate"].mean()

plt.figure(figsize=(15,8))
plt.bar(illiteracy.index,illiteracy.values)
plt.bar(literacy.index, literacy.values, alpha=0.7)
plt.title("Illiterates and Literates trand over Years")
plt.xlabel("Year")
plt.ylabel("Trend")
plt.legend(["Illiterates", "Literates"])
plt.yticks(range(0, 101, 10))
plt.grid(alpha=0.5)

plt.show()

"""**6. Illiteracy Rate comparision betweeen selected countries over years**"""

countries = ["Bangladesh", "China", "India", "Nepal", "Pakistan"]

com_countries = df_illiteracy[df_illiteracy["Country"].isin(countries)]

plt.figure(figsize=(15,8))
sns.barplot(data=com_countries, x="Year", y="Illiteracy_rate", palette= "magma", width=1, hue="Country")

plt.title("Illiteracy Rate of Five Countries(random)")
plt.xlabel("Year")
plt.ylabel("Illiteracy Rate")
plt.legend(loc="upper right")

plt.grid(False)

plt.show()

"""***GDP and Schooling EDA***

**7. GPD per Avg Schooling**
"""

plt.figure(figsize=(15,6))

sns.scatterplot(data = df_gdp_schooling, x="Avg_yrs_schooling", y="GDP")

plt.title("GDP vs Schooling")
plt.xlabel("Schooling")
plt.ylabel("GDP")
plt.grid(True, alpha=0.5)


plt.show()

"""**8. Highest GDP countries literacy rate TOP 5 only**"""

top_gdp = df_gdp_schooling.groupby("Country")[["GDP", "Literacy"]] \
                          .mean() \
                          .sort_values(by="GDP", ascending=False) \
                          .head(5) #\ line continue

plt.figure(figsize=(15,8))

sns.barplot(x = top_gdp.index, y = top_gdp["Literacy"], palette = "viridis", hue = top_gdp["GDP"],
            width = 0.25)

plt.title("Literacy Rate of Highest GDP Countries")
plt.xlabel("Country")
plt.ylabel("Literacy Rate")
plt.grid(False)

plt.show()

"""**9. Literacy Growth Rate over year - India.**"""

ind = df_gdp_schooling[df_gdp_schooling["Country"] == "India"].copy()
growth = ind.groupby("Year")["Growth_Rate"].mean().reset_index()

fig = px.line(growth, x="Year", y="Growth_Rate", title="Literacy Growth Rate over year - India", markers=True, line_shape='spline')

fig.update_layout(width=1000, height=600, title_x=0.5)
fig.update_traces(line=dict(color='orange', width=4))

fig.show()

"""**10. Population Growth vs Literacy Growth - Covid**"""

covid = df_gdp_schooling[(df_gdp_schooling["Year"] >= 2020) & (df_gdp_schooling["Year"] <= 2023)]

population_literacy = covid.groupby("Year", as_index=False).agg ({"Population": "max", "Literacy": "mean"})

population_literacy["Year"] = population_literacy["Year"].astype(int)

fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(go.Bar(x=population_literacy["Year"],y=population_literacy["Population"] / 1_000_000,name="Population (Million)"),secondary_y=False)

fig.add_trace(go.Scatter(x=population_literacy["Year"], y=population_literacy["Literacy"], mode="lines+markers", name="Literacy Rate (%)"), secondary_y=True)

fig.update_layout(title="Population Growth vs Literacy Growth - Covid",width=900, height=600, template="plotly_white")

fig.update_xaxes(title_text="Year")
fig.update_yaxes (title_text="Population (Millions)", secondary_y=False)
fig.update_yaxes(title_text="Literacy Rate (%)", secondary_y=True)

fig.show()

"""**11. GDP Distribution Boxplot**"""

plt.figure(figsize=(15,8))

sns.boxplot(
    data=df_gdp_schooling,
    x="Year",
    y="GDP",
    palette="viridis",
    hue = "Year"
)

plt.title("GDP Distribution Over Years")
plt.xlabel("Year")
plt.ylabel("GDP")

plt.xticks(rotation=45)

plt.grid(alpha=0.5)

plt.show()

"""**12. Correlation of Population and Literacy**"""

df_gdp_schooling = df_gdp_schooling.sort_values(["Year", "Population"])

population_literacy = df_gdp_schooling.groupby("Year", as_index=False).agg ({"Population": "max", "Literacy": "mean"})

fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(go.Bar(x=population_literacy["Year"],y=population_literacy["Population"] / 1_000_000,name="Population (Million)"),secondary_y=False)
fig.add_trace(go.Scatter(x=population_literacy["Year"], y=population_literacy["Literacy"], mode="lines+markers", name="Literacy Rate (%)"), secondary_y=True)
fig.update_layout(title="Population vs Literacy Rate Over Years",width=1100, height=600, title_x=0.5, template="plotly_white")

fig.update_xaxes(title_text="Year")
fig.update_yaxes (title_text="Population (Millions)", secondary_y=False)
fig.update_yaxes(title_text="Literacy Rate (%)", secondary_y=True)

fig.show()

"""# **SQL Connection and Pusing**"""

pip install mysql-connector-python

import mysql.connector

conn = mysql.connector.connect(
    host = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com",
    user = "3fXqCw6nxxduoS8.root",
    password = "u2dctQHUVuOXcZhS",
    port = 4000
)

gl = conn.cursor()

gl.execute("DROP DATABASE IF EXISTS Global_Literacy")
conn.commit()

gl.execute("CREATE DATABASE Global_Literacy")
conn.commit()

gl.execute("show databases")
gl.fetchall()

gl.execute("use Global_Literacy")

gl.execute("""CREATE TABLE literacy_rates(
              Country VARCHAR(100),
              Code CHAR(10),
              Year INT,
              Adult FLOAT,
              Male FLOAT,
              Female FLOAT,
              Region VARCHAR(50),
              Population FLOAT,
              Literacy_gap FLOAT,
              Total_Youth FLOAT,
              Avg_Youth_Literacy FLOAT,

              PRIMARY KEY (Country, Year)
              )""")

conn.commit()

gl.execute("""CREATE TABLE illiteracy_population(
              Country VARCHAR(100),
              Code CHAR(10),
              Year INT,
              Illiteracy_rate FLOAT,
              Literacy_rate FLOAT,
              Population FLOAT,
              Illiteracy_Population FLOAT,

              PRIMARY KEY (Country, Year),

              FOREIGN KEY (Country, Year)
              REFERENCES literacy_rates(Country, Year)
              )""")

conn.commit()

gl.execute("""CREATE TABLE gdp_schooling(
              Country VARCHAR(100),
              Code CHAR(10),
              Year INT,
              Region VARCHAR(50),
              GDP FLOAT,
              Literacy FLOAT,
              Avg_yrs_schooling FLOAT,
              Population FLOAT,
              GDP_per_Schooling FLOAT,
              Education_Index FLOAT,
              Growth_Rate FLOAT,

              PRIMARY KEY (Country, Year)
              )""")

conn.commit()

gl.execute("show tables")
gl.fetchall()

"""**Pushing DaraFrame to SQL**"""

pip install pandas sqlalchemy mysql-connector-python

from sqlalchemy import create_engine

engine = create_engine("mysql+mysqlconnector://3fXqCw6nxxduoS8.root:u2dctQHUVuOXcZhS@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/Global_Literacy")

df_literacy.to_sql("literacy_rates", con=engine, if_exists="append", index=False)

df_illiteracy.to_sql("illiteracy_population", con=engine, if_exists="append", index=False)

df_gdp_schooling.to_sql("gdp_schooling", con=engine, if_exists="append", index=False)

"""# SQL Query"""

engine = create_engine("mysql+mysqlconnector://3fXqCw6nxxduoS8.root:u2dctQHUVuOXcZhS@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/Global_Literacy")

"""**literacy_rates**"""

# 1. Get top 5 countries with highest adult literacy in 2020.

top_5_countries = pd.read_sql ("""SELECT Country, MAX(Adult) AS Top_5_Countries
FROM literacy_rates WHERE Year = 2020
AND Adult IS NOT NULL
GROUP BY Country
ORDER BY Top_5_Countries DESC
LIMIT 6;""", engine)

top_5_countries

# 2. Find countries where female youth literacy < 80%.

female_literacy = pd.read_sql ("""SELECT Country, Female
FROM literacy_rates
WHERE Female < 80;""", engine)

female_literacy

# 3. Average adult literacy per continent (owid region).

avg_adult_literacy = pd.read_sql ("""SELECT Region, AVG(Adult) AS Avg_Adult_Literacy
FROM literacy_rates
GROUP BY Region;""", engine)

avg_adult_literacy

"""**illiteracy_population**"""

# 4. Countries with illiteracy % > 20% in 2000.

countries_lower_illiteracy = pd.read_sql ("""SELECT Country, Year, Illiteracy_rate
FROM illiteracy_population
WHERE Year = 2000 AND Illiteracy_rate > 20
ORDER BY Illiteracy_rate ASC;""", engine)

countries_lower_illiteracy

# 5. Trend of illiteracy % for India (2000–2020).

india_illiteracy = pd.read_sql ("""SELECT Year, Illiteracy_rate
FROM illiteracy_population
WHERE Country = 'India'
AND Year BETWEEN 2000 AND 2020;""", engine)

india_illiteracy

# 6. Top 10 countries with largest illiterate population in the last year.

top_10_illiterate = pd.read_sql ("""SELECT Country, MAX(Illiteracy_Population) AS Illiterate
FROM illiteracy_population
WHERE Year = 2023
AND Illiteracy_Population IS NOT NULL
GROUP BY Country
ORDER BY IlliTerate DESC
LIMIT 11;""", engine)

top_10_illiterate

"""**gdp_schooling**"""

# 7. Find countries with avg_years_schooling > 7 and gdp_per_capita < 5000.

avg_schooling_gdp = pd.read_sql (""" SELECT Country, Avg_yrs_schooling, GDP
FROM gdp_schooling
WHERE Avg_yrs_schooling > 7 AND GDP < 5000
AND Avg_yrs_schooling is NOT NULL
AND GDP is NOT NULL;""", engine)

avg_schooling_gdp

# 8. Rank countries by GDP per schooling for the year 2020.

rank_gdp_schooling = pd.read_sql (""" SELECT Country, GDP_per_Schooling
FROM gdp_schooling
WHERE Year = 2020
AND GDP_per_Schooling IS NOT NULL
ORDER BY GDP_per_Schooling DESC;""", engine)

rank_gdp_schooling

# 9. Find global average schooling years per year.

global_avg_schooling = pd.read_sql (""" SELECT Year, AVG(Avg_yrs_schooling) AS Avg_Schooling
FROM gdp_schooling
WHERE Avg_yrs_schooling IS NOT NULL
GROUP BY Year
ORDER BY Year ASC;""", engine)

global_avg_schooling

"""**Join Queries**"""

# 10. List top 10 countries in 2020 with highest GDP per capita but lowest average years of schooling(less than 6).

top_10_gdp_schooling = pd.read_sql (""" SELECT Country, GDP_per_Schooling, Avg_yrs_schooling
FROM gdp_schooling
WHERE Year = 2020
AND Avg_yrs_schooling < 6
AND GDP_per_Schooling IS NOT NULL
ORDER BY GDP_per_Schooling DESC
LIMIT 11;""", engine)

top_10_gdp_schooling

# 11. Show countries where the illiterate population is high despite having more than 10 average years of schooling.

illiterate_schooling = pd.read_sql (""" SELECT i.Country, i.Illiteracy_Population, g.Avg_yrs_schooling, i.Year
FROM illiteracy_population i
JOIN gdp_schooling g ON i.Country = g.Country
WHERE g.Avg_yrs_schooling > 10
AND i.Illiteracy_Population IS NOT NULL
ORDER BY i.Illiteracy_Population DESC;""", engine)

illiterate_schooling

# 12. Compare literacy rates and GDP per capita growth for a selected country over the last 20 years. (country of your choice)

slt_country = pd.read_sql (""" SELECT l.Country, l.Year, l.Avg_Youth_Literacy, g.Growth_Rate
FROM literacy_rates l
JOIN gdp_schooling g ON l.Country = g.Country AND l.Year = g.Year
WHERE l.Country = 'India'
AND l.year BETWEEN 2000 AND 2023
AND l.Avg_Youth_Literacy IS NOT NULL
AND g.GDP_per_Schooling IS NOT NULL
ORDER BY l.Year ASC;""", engine)

slt_country

literacy  = pd.read_sql ("""SELECT g.Country, g.Year, g.Literacy, l.Adult
FROM gdp_schooling g
JOIN literacy_rates l ON g.Country = l.Country AND g.Year = l.Year
WHERE g.Year BETWEEN 1990 AND 2023
AND g.Country = 'Pakistan'
AND g.Literacy IS NOT NULL
AND l.Adult IS NOT NULL
ORDER BY g.Year ASC""", engine)

literacy

# 13. Show the difference between youth literacy male and female rates for countries with GDP per capita above $30,000 in 2020.

difference = pd.read_sql (""" SELECT l.Country, l.Year, l.Male, l.Female, g.GDP
FROM literacy_rates l
JOIN gdp_schooling g ON l.Country = g.Country AND l.Year = g.Year
WHERE g.Year = 2020
AND g.GDP > 30000
AND l.Male IS NOT NULL
AND l.Female IS NOT NULL
AND g.GDP IS NOT NULL
ORDER BY g.GDP DESC;""", engine)

difference

"""# Streamlit"""

!pip install streamlit pyngrok

from pyngrok import ngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# from pyngrok import ngrok
# 
# # importing libraries
# import streamlit as st
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns
# import plotly.express as px
# from plotly.subplots import make_subplots
# import plotly.graph_objects as go
# import mysql.connector
# from sqlalchemy import create_engine
# import time
# 
# # connecting with sql
# mydb = mysql.connector.connect(
#     host="gateway01.ap-southeast-1.prod.aws.tidbcloud.com",
#     user="3fXqCw6nxxduoS8.root",
#     password="u2dctQHUVuOXcZhS",
#     database="Global_Literacy"
# )
# 
# 
# # load data
# @st.cache_data
# def load_data():
#     literacy = pd.read_sql("SELECT * FROM literacy_rates", mydb)
#     illiteracy = pd.read_sql("SELECT * FROM illiteracy_population", mydb)
#     gdp_schooling = pd.read_sql("SELECT * FROM gdp_schooling", mydb)
#     return literacy, illiteracy, gdp_schooling
# 
# literacy, illiteracy, gdp_schooling = load_data()
# 
# # main page setup
# st.set_page_config(page_title="Global Literacy and GDP ", layout="wide")
# st.title("🧠💰Global Literacy and GDP Dashboard")
# st.subheader("Welcome to the Global Literacy Dashboard!👋")
# st.markdown("""This dashboard provides insights into global literacy rates, illiteracy population, and the relationship between GDP and schooling years.
# Use the sidebar to navigate through different sections.""")
# 
# # side bar
# st.sidebar.title("Menu")
# page = st.sidebar.selectbox(
#     "Options",
#     [ "SQL Query Executor", "EDA Visualizations", "Country Profile Page"])
# 
# #page 1: sql query page
# if page == "SQL Query Executor":
#   st.title("SQL Query Executor")
# 
#   queries = {
#       "Literacy Rates and Trends":{
#           "Top 5 Countries with Highest Adult Literacy in 2020":{
#               "query":
#               """SELECT Country, MAX(Adult) AS Highest_Adult FROM literacy_rates
#               WHERE Year = 2020 AND Adult IS NOT NULL
#               GROUP BY Country ORDER BY Highest_Adult DESC LIMIT 6;""",
# 
#               "chart": "bar",
#               "x": "Country",
#               "y": "Highest_Adult"
#               },
# 
#           "Countries where Female Youth Literacy were < 80pct":{
#               "query":
#               """SELECT Country, Female FROM literacy_rates WHERE Female < 80;""",
# 
#               "chart": "bar",
#               "x": "Country",
#               "y": "Female"
#               },
# 
#           "Average Adult Literacy per Continent":{
#               "query":
#               """SELECT Region, AVG(Adult) AS Avg_Adult_Literacy FROM literacy_rates GROUP BY Region;""",
#               "chart": "pie",
#               "x": "Region",
#               "y": "Avg_Adult_Literacy"
#               }
#           },
# 
#       "Illiteracy Population Analysis": {
#           "Countries with illiteracy rate > 20pct in 2000":{
#               "query":
#               """SELECT Country, Year, Illiteracy_rate FROM illiteracy_population
#               WHERE Year = 2000 AND Illiteracy_rate > 20 ORDER BY Illiteracy_rate ASC;""",
# 
#               "chart": "bar",
#               "x": "Country",
#               "y": "Illiteracy_rate"
#               },
# 
#           "Trend of illiteracy rate for India (2000 to 2020)": {
#               "query":
#               """SELECT Year, Illiteracy_rate FROM illiteracy_population WHERE Country = 'India' AND Year BETWEEN 2000 AND 2020;""",
#               "chart": "line",
#               "x": "Year",
#               "y": "Illiteracy_rate"
#               },
#           "Top 10 countries with largest illiterate population in the last year": {
#               "query":
#               """SELECT Country, MAX(Illiteracy_Population) AS Illiterate FROM illiteracy_population WHERE Year = 2023
#               AND Illiteracy_Population IS NOT NULL GROUP BY Country ORDER BY Illiterate DESC LIMIT 10;""",
# 
#               "chart": "bar",
#               "x": "Country",
#               "y": "Illiterate"
#               }
#           },
# 
#       "GDP and Schooling Analysis": {
#           "Countries with avg_years_schooling > 7 and gdp_per_capita < 5000":{
#               "query":
#               """SELECT Country, Avg_yrs_schooling, GDP FROM gdp_schooling
#               WHERE Avg_yrs_schooling > 7 AND GDP < 5000 AND Avg_yrs_schooling is NOT NULL AND GDP is NOT NULL;""",
# 
#               "chart": "scatter",
#               "x": "Avg_yrs_schooling",
#               "y": "GDP"
#               },
# 
#           "Ranking countries by GDP per schooling for the year 2020":{
#               "query": """SELECT Country, GDP_per_Schooling FROM gdp_schooling
#               WHERE Year = 2020 AND GDP_per_Schooling IS NOT NULL ORDER BY GDP_per_Schooling DESC;""",
# 
#               "chart": "scatter",
#               "x": "Country",
#               "y": "GDP_per_Schooling"
#               },
# 
#           "Find global average schooling years per year":{
#               "query": """SELECT Year, AVG(Avg_yrs_schooling) AS Avg_Schooling FROM gdp_schooling
#               WHERE Avg_yrs_schooling IS NOT NULL GROUP BY Year ORDER BY Year ASC;""",
# 
#               "chart": "line",
#               "x": "Year",
#               "y": "Avg_Schooling"
#               }
#       },
# 
#       "Additional Queries": {
#           "Top 10 countries in 2020 with highest GDP per capita but lowest average years of schooling(less than 6)" : {
#               "query": """SELECT Country, GDP_per_Schooling, Avg_yrs_schooling FROM gdp_schooling WHERE Year = 2020
#               AND Avg_yrs_schooling < 6 AND GDP_per_Schooling IS NOT NULL ORDER BY GDP_per_Schooling DESC LIMIT 11;""",
# 
#               "chart": "bar",
#               "x": "Country",
#               "y": "GDP_per_Schooling"
#               },
# 
#           "Countries where the illiterate population is high despite having more than 10 average years of schooling" :{
#               "query": """SELECT i.Country, i.Illiteracy_Population, g.Avg_yrs_schooling, i.Year FROM illiteracy_population i
#               JOIN gdp_schooling g ON i.Country = g.Country WHERE g.Avg_yrs_schooling > 10 AND i.Illiteracy_Population IS NOT NULL
#               ORDER BY i.Illiteracy_Population DESC;""",
# 
#               "chart": "scatter",
#               "x": "Avg_yrs_schooling",
#               "y": "Illiteracy_Population"
#               },
# 
#           "Compare literacy rates and GDP per capita growth for India" :{
#               "query": """SELECT l.Country, l.Year, l.Avg_Youth_Literacy, g.Growth_Rate FROM literacy_rates l JOIN gdp_schooling g ON l.Country = g.Country
#               AND l.Year = g.Year WHERE l.Country = 'India' AND l.year BETWEEN 2000 AND 2023 AND l.Avg_Youth_Literacy IS NOT NULL
#               AND g.GDP_per_Schooling IS NOT NULL ORDER BY l.Year ASC;""",
# 
#               "chart": "line",
#               "x": "Year",
#               "y": "Growth_Rate"
#               },
#           "Countries with high GDP and Difference in Literacy(Male, Female)" : {
#               "query": """SELECT l.Country, l.Year, l.Male, l.Female, g.GDP FROM literacy_rates l JOIN gdp_schooling g ON l.Country = g.Country
#               AND l.Year = g.Year WHERE g.Year = 2020 AND g.GDP > 30000 AND l.Male IS NOT NULL AND l.Female IS NOT NULL
#               AND g.GDP IS NOT NULL ORDER BY g.GDP DESC;""",
#               "chart": "grouped_bar",
#               "x": "Country",
#               "y1": "Male",
#               "y2": "Female"
#               }
#           }
#       }
# 
#   category = st.selectbox("Select Category", list(queries.keys()))
#   query_name = st.selectbox("Select Query", list(queries[category].keys()))
# 
#   if st.button("Run Query"):
#     with st.spinner("Running query..."):
#       time.sleep(2)
#     query_info = queries[category][query_name]
#     query = query_info["query"]
# 
#     result = pd.read_sql(query, mydb)
# 
#     st.dataframe(result)
# 
#     st.subheader("📊 Query Visualization")
#     chart_type = query_info["chart"]
#     x_col = query_info["x"]
#     y_col = query_info.get("y")
# 
#     # BAR
#     if chart_type == "bar":
#       fig = px.bar(result,
#                    x=x_col,
#                    y=y_col,
#                    text_auto=True,
#                    color=y_col
#                    )
# 
#     elif chart_type == "line":
#       fig = px.line(result,
#                     x=x_col,
#                     y=y_col,
#                     markers=True)
# 
#     elif chart_type == "pie":
#       fig = px.pie(result,
#                    names=x_col,
#                    values=y_col)
# 
#     elif chart_type == "scatter":
#       fig = px.scatter(result,
#                        x=x_col,
#                        y=y_col)
# 
#     elif chart_type == "grouped_bar":
#       fig = px.bar(result,
#                    x=x_col,
#                    y=[query_info["y1"], query_info["y2"]],
#                    barmode="group"
#                    )
# 
#     st.plotly_chart(fig, use_container_width=True)
# 
# 
# # page 2:
# elif page == "EDA Visualizations":
# 
#     st.title("📊 EDA Visualizations")
# 
#     eda_options = [
#         "Adult & Youth Literacy Rate Over Years",
# 
#         "Region wise Male and Female Literacy Rate",
# 
#         "Adult Literacy during covid (2020 to 2023)",
# 
#         "Illiteracy Rate comparision betweeen selected countries over years",
# 
#         "Illiterates vs Literates trend over Years",
# 
#         "GDP per Avg Schooling",
# 
#         "Highest GDP countries literacy rate TOP 5 only",
# 
#         "Literacy Growth Rate over year - India.",
# 
#         "GDP Distribution Boxplot",
# 
#         "Correlation of Population and Literacy"
#     ]
# 
#     eda_name = st.selectbox("Select Category",eda_options)
# 
#     def show_chart(fig):
# 
#         st.plotly_chart( fig, use_container_width=True)
# 
#     # 1
#     if eda_name == "Adult & Youth Literacy Rate Over Years":
#       adult_literacy = literacy.groupby("Year")["Adult"].mean()
#       youth_literacy = literacy.groupby("Year")["Total_Youth"].mean()
# 
#       fig, ax = plt.subplots(figsize=(15, 8))
# 
#       ax.plot(youth_literacy.index, youth_literacy.values, label="Youth")
#       ax.plot(adult_literacy.index, adult_literacy.values, label="Adult")
# 
#       ax.set_title("Avg Literacy Rate Over Years of Adult & Youth")
#       ax.set_xlabel("Year")
#       ax.set_ylabel("Literacy Rate")
# 
#       ax.legend()
#       ax.grid(alpha=0.5)
# 
#       show_chart(fig)
# 
#     # 2
#     elif eda_name == "Region wise Male and Female Literacy Rate":
#       r_male_literacy = literacy.groupby("Region")["Male"].mean()
#       r_female_literacy = literacy.groupby("Region")["Female"].mean()
# 
#       fig, ax = plt.subplots(figsize=(15,8))
#       ax.plot(r_male_literacy.index, r_male_literacy.values, marker="o")
#       ax.plot(r_female_literacy.index, r_female_literacy.values, marker="o")
#       ax.set_title("Region Wise Trend")
#       ax.set_xlabel("Region")
#       ax.set_ylabel("Total_Youth")
#       ax.grid(alpha=0.5)
#       ax.legend(["Male", "Female"])
# 
#       st.pyplot(fig)
# 
#     # 3
#     elif eda_name == "Adult Literacy during covid (2020 to 2023)":
#       covid_year = literacy[(literacy["Year"] >= 2020) & (literacy["Year"] <= 2023)]
#       adult_literacy = covid_year.groupby("Year", as_index=False)["Adult"].mean().round()
# 
#       fig, ax = plt.subplots(figsize=(15,8))
# 
#       sns.barplot(data=adult_literacy, x="Year", y="Adult", palette="dark", ax=ax)
# 
#       ax.set_title("Adult Literacy During COVID (2020 to 2023)")
#       ax.set_xlabel("Year")
#       ax.set_ylabel("Adult Literacy")
#       ax.legend(loc="upper center")
# 
#       st.pyplot(fig)
# 
#     # 4
#     elif eda_name == "Illiteracy Rate comparision betweeen selected countries over years":
#         countries = ["Bangladesh", "China", "India", "Nepal", "Pakistan"]
# 
#         com_countries = illiteracy[illiteracy["Country"].isin(countries)]
# 
#         fig, ax = plt.subplots(figsize=(15, 8))
# 
#         sns.barplot(data=com_countries, x="Year", y="Illiteracy_rate", palette="magma", ax=ax)
# 
#         ax.set_title("Illiteracy Rate of Five Countries")
#         ax.set_xlabel("Year")
#         ax.set_ylabel("Illiteracy Rate")
# 
#         ax.legend(loc="upper right")
#         ax.grid(False)
# 
#         st.pyplot(fig)
# 
#     # 5
#     elif eda_name == "Illiterates vs Literates trend over Years":
# 
#         data = illiteracy.groupby("Year", as_index=False)[["Illiteracy_rate", "Literacy_rate"]].mean()
# 
#         fig = px.line(data, x="Year", y=["Illiteracy_rate", "Literacy_rate"], markers=True)
# 
#         show_chart(fig)
# 
#     # 6
#     elif eda_name == "GDP per Avg Schooling":
# 
#         fig = px.scatter(gdp_schooling, x="Avg_yrs_schooling", y="GDP", color="Region")
# 
#         show_chart(fig)
# 
#     # 7
#     elif eda_name == "GDP Distribution Boxplot":
# 
#         fig = px.box(gdp_schooling, x="Year", y="GDP")
# 
#         show_chart(fig)
# 
#     # 8
#     elif eda_name == "Correlation of Population and Literacy":
#       data = gdp_schooling[(gdp_schooling["Year"] >= 2020) & (gdp_schooling["Year"] <= 2023)]
#       df = data.groupby("Year", as_index=False).agg({"Population": "mean", "Literacy": "mean"})
#       df["Population_Million"] = df["Population"] / 1_000_000
# 
#       fig = make_subplots(specs=[[{"secondary_y": True}]])
# 
#       # Population bar
#       fig.add_trace(go.Bar(x=df["Year"],y=df["Population_Million"],name="Population (Million)"),secondary_y=False)
# 
#       # Literacy line (IMPORTANT FIX HERE)
#       fig.add_trace(go.Scatter(x=df["Year"],y=df["Literacy"],mode="lines+markers",name="Literacy Rate (%)"),secondary_y=True)
# 
#       fig.update_layout(title="Population Growth vs Literacy Growth (2020–2023)", width=900, height=600, template="plotly_white")
# 
#       fig.update_xaxes(title_text="Year")
# 
#       fig.update_yaxes(title_text="Population (Millions)", secondary_y=False)
# 
#       fig.update_yaxes(title_text="Literacy Rate (%)", secondary_y=True, range=[0, 100])
# 
#       show_chart(fig)
# 
#     # 9
#     elif eda_name == "Highest GDP countries literacy rate TOP 5 only":
#       data = gdp_schooling.groupby( "Country", as_index=False )[["GDP", "Literacy"]].mean()
# 
#       #top 5
#       data = data.sort_values( by="GDP", ascending=False ).head(5)
# 
#       fig = px.bar(data, x="Country", y=["GDP", "Literacy"], barmode="group")
# 
#       show_chart(fig)
# 
#     # 10
#     elif eda_name == "Literacy Growth Rate over year - India.":
# 
#         data = literacy[
#             literacy["Country"] == "India"][["Year", "Adult", "Avg_Youth_Literacy"]]
# 
#         fig = px.line(data, x="Year", y=["Adult", "Avg_Youth_Literacy"], markers=True)
# 
#         show_chart(fig)
# 
# # PAGE 3
# elif page == "Country Profile Page":
# 
#     st.title("🌍 Country Profile Page")
#     country = st.selectbox("Select Country", sorted(literacy["Country"].unique()))
#     row1_col1, row1_col2 = st.columns(2)
#     row3_col1, row3_col2 = st.columns(2)
# 
# 
# 
#     # filter data
#     literacy_data = literacy[literacy["Country"] == country]
# 
#     illiteracy_data = illiteracy[illiteracy["Country"] == country]
# 
#     gdp_data = gdp_schooling[gdp_schooling["Country"] == country]
# 
#     # Literacy Trend
#     with row1_col1:
#       st.subheader("📘 Literacy Trends")
#       fig1 = px.line( literacy_data, x="Year", y=["Adult", "Avg_Youth_Literacy"], markers=True, title=f"{country} Literacy Trends")
# 
#       st.plotly_chart( fig1, use_container_width=True )
# 
#     # GDP Trend
#     with row1_col2:
#       st.subheader("💰 GDP Trend")
#       fig2 = px.line(gdp_data, x="Year", y="GDP", markers=True, title=f"{country} GDP Over Years")
# 
#       st.plotly_chart(fig2, use_container_width=True)
# 
#     # Schooling Trend
#     st.subheader("🎓 Average Schooling Years")
# 
#     fig3 = px.line(gdp_data, x="Year", y="Avg_yrs_schooling", markers=True, title=f"{country} Schooling Trend")
# 
#     st.plotly_chart(fig3,use_container_width=True)
# 
#     # Population Trend
#     with row3_col1:
#       st.subheader("👨‍👩‍👧 Population Trend")
# 
#       fig4 = px.bar(gdp_data, x="Year", y="Population", title=f"{country} Population")
# 
#       st.plotly_chart(fig4, use_container_width=True)
# 
#     # Illiteracy Trend
#     with row3_col2:
#       st.subheader("📉 Illiteracy Trend")
# 
#       fig5 = px.line(illiteracy_data, x="Year", y="Illiteracy_rate", markers=True, title=f"{country} Illiteracy Trend")
# 
#       st.plotly_chart(fig5,use_container_width=True)
# 
#

ngrok.set_auth_token("3DfZN4RcDTbGEZxx7cfRRAi045e_5xLeR6pKV57CM634VJbgt")

!streamlit run app.py &>/content/logs.txt &

public_url = ngrok.connect(8501)
print(public_url)